# Generated by Django 5.1.4 on 2025-03-27 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_dean', models.BooleanField(default=False)),
                ('is_headdept', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDefense',
            fields=[
                ('applicationID', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('research_title', models.TextField(blank=True, null=True)),
                ('lead_researcher', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_contactno', models.CharField(blank=True, max_length=15, null=True)),
                ('co_researcher', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher1', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher2', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher3', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher4', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_defense', models.CharField(blank=True, max_length=255, null=True)),
                ('place_defense', models.CharField(blank=True, max_length=255, null=True)),
                ('documenter', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='defense_application/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_defenses', to=settings.AUTH_USER_MODEL)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_adviser', to='users.faculty')),
                ('panel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_panel1', to='users.faculty')),
                ('panel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_panel2', to='users.faculty')),
                ('panel3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_panel3', to='users.faculty')),
                ('panel_chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_chair', to='users.faculty')),
            ],
            options={
                'verbose_name': 'Application Defense',
                'verbose_name_plural': 'Student Application Defenses',
            },
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('manuscriptID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the manuscript', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description or abstract of the manuscript')),
                ('pdf', models.FileField(help_text='Upload the PDF file here', upload_to='manuscripts/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manuscript',
                'verbose_name_plural': 'Student Manuscripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelDefense',
            fields=[
                ('panelID', models.AutoField(primary_key=True, serialize=False)),
                ('research_title', models.TextField(blank=True, null=True)),
                ('lead_researcher', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher1', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher2', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher3', models.CharField(blank=True, max_length=255, null=True)),
                ('co_researcher4', models.CharField(blank=True, max_length=255, null=True)),
                ('docx_file', models.FileField(upload_to='panel_nomination/')),
                ('pdf_file', models.FileField(upload_to='panel_nomination/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_adviser', to='users.faculty')),
                ('panel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_panel1', to='users.faculty')),
                ('panel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_panel2', to='users.faculty')),
                ('panel3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_panel3', to='users.faculty')),
                ('panel_chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_chair', to='users.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_defenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panel Defense',
                'verbose_name_plural': 'Student Panel Defenses',
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('application_defense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.applicationdefense')),
                ('panel_defense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.paneldefense')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.faculty')),
            ],
            options={
                'verbose_name': 'Submission Review',
                'verbose_name_plural': 'Submission Reviews',
            },
        ),
    ]
