# Generated by Django 5.1.4 on 2025-03-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelDefense',
            new_name='PanelApplication',
        ),
        migrations.RenameField(
            model_name='submissionreview',
            old_name='panel_defense',
            new_name='panel_application',
        ),
    ]
