# Generated by Django 5.1.4 on 2025-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelDefense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('docx_file', models.FileField(upload_to='panel_nomination/')),
                ('pdf_file', models.FileField(upload_to='panel_nomination/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Defense',
                'verbose_name_plural': 'Application Defenses',
            },
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='docx_file',
            field=models.FileField(upload_to='defense_application/'),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='pdf_file',
            field=models.FileField(upload_to='defense_application/'),
        ),
    ]
