# Generated by Django 5.1.4 on 2025-01-31 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the manuscript', max_length=200)),
                ('pdf', models.FileField(help_text='Upload the PDF file here', upload_to='manuscripts/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of submission')),
            ],
            options={
                'verbose_name': 'Manuscript',
                'verbose_name_plural': 'Manuscripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
