# Generated by Django 5.1.4 on 2025-03-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdefense',
            old_name='user',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='user',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='paneldefense',
            old_name='user',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_adviser', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='datetime_defense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='panel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_panel1', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='panel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_panel2', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='panel3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_panel3', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='panel_chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_chair', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='paneldefense',
            name='panel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_panel1', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='paneldefense',
            name='panel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_panel2', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='paneldefense',
            name='panel3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_panel3', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='paneldefense',
            name='panel_chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_chair', to='users.faculty'),
        ),
    ]
