# Generated by Django 5.1.4 on 2025-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdefense',
            options={'verbose_name': 'Application Defense', 'verbose_name_plural': 'Student Application Defenses'},
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='adviser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='co_researcher1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='co_researcher2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='co_researcher3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='co_researcher4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='co_researcher5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='datetime_defense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='documenter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='lead_contactno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='lead_researcher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='panel1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='panel2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='panel3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='panel_chair',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='place_defense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationdefense',
            name='research_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='defense_application/'),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdefense',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='defense_application/'),
        ),
    ]
