# Generated by Django 5.1.4 on 2025-03-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paneldefense_alter_applicationdefense_docx_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paneldefense',
            options={'verbose_name': 'Panel Defense', 'verbose_name_plural': 'Panel Defenses'},
        ),
    ]
