# Generated by Django 5.1.4 on 2025-03-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_applicationdefense_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdefense',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paneldefense',
            old_name='userID',
            new_name='user',
        ),
    ]
