# Generated by Django 5.1.4 on 2025-03-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_rename_paneldefense_panelapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='submissionreview',
            name='application_defense',
        ),
        migrations.RemoveField(
            model_name='submissionreview',
            name='panel_application',
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
