# Generated by Django 5.1.4 on 2025-03-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_applicationdefense_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdefense',
            old_name='co_researcher5',
            new_name='co_researcher',
        ),
    ]
