# Generated by Django 5.1.4 on 2025-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_co_researcher5_applicationdefense_co_researcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paneldefense',
            options={},
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='adviser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='co_researcher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='co_researcher1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='co_researcher2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='co_researcher3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='co_researcher4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='lead_researcher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='panel1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='panel2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='panel3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='panel_chair',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paneldefense',
            name='research_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paneldefense',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paneldefense',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
