# Generated by Django 5.1.4 on 2025-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_manuscript_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('deans_office', 'Dean’s Office/Dean'), ('head_department', 'Head of Department'), ('faculty', 'Faculty/Panels'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
